### ISSUE TITLE
Domain Permutation in methods.py

### ISSUE THREAD

**Issue by mvp18** [mancinimassimiliano/CuMix#3]
Hi @mancinimassimiliano,

Below is the **get_sample_mixup** function on L237 in methods.py:

```
def get_sample_mixup(self, domains):
        # Check how many domains are in each batch (if 1 skip, but we have 1 just in ZSL only exps)
        if self.dpb>1:
            doms = list(range(len(torch.unique(domains))))
            bs = domains.size(0) // len(doms)
            selected = derange(doms)
            permuted_across_dom = torch.cat([(torch.randperm(bs) + selected[i] * bs) for i in range(len(doms))])
            permuted_within_dom = torch.cat([(torch.randperm(bs) + i * bs) for i in range(len(doms))])
            ratio_within_dom = torch.from_numpy(RG.binomial(1, self.mixup_domain, size=domains.size(0)))
            indeces = ratio_within_dom * permuted_within_dom + (1. - ratio_within_dom) * permuted_across_dom
        else:
            indeces = torch.randperm(domains.size(0))
        return indeces.long()
```

As I understand for domains per batch > 1, depending on ratio_within_dom (1 or 0) this function returns indices for mixup either within or across domains. However, I can't understand how the 2 tensors **permuted_across_dom** and **permuted_within_dom** ensure that the batch indices are properly re-arranged to achieve this. I have tried with some dummy inputs, but couldn't figure out the exact logic. Would like to hear your thoughts on this.

**Comment by mancinimassimiliano** [comment]
Hello @mvp18,

The function works under the assumption that one batch is balanced and ordered across domains (as ensured dy the `BalancedSampler`). As an example, if you have 3 domains [a,b,c] and batch size 6, your batch size will have the following (pseudo-)structure:
`[a1,a2,
 b1,b2,
 c1,c2]`
 

 where `dN` indicates the Nth sample of domain d. Given this, following the code is simple:
 - `doms` is the list of indices of domains in the batch (i.e. `doms=[0,1,2]` in the example above)
 - `domains.size(0)` is the batch size (i.e. 6 above)
 - `bs = domains.size(0) // len(doms)` which is equal to 6/3=2 in the example. 
 - `selected = derange(doms)` is a permuted version of `doms` where it is ensured (by `derange`) that none of the indices remains in the same position (e.g. in the example above it will return either `[1,2,0]` or `[2,0,1])`
 
The final thing to highlight is that, from the structure and definitions above, the first sample of a domain with index `i` starts at position `bs*i` while the last sample is `bs*(i+1)-1`. Now `permuted_within_dom` is obtained by:
 - randomly permuting a list of indices going from 0 to `bs-1`: this is what  `torch.randperm(bs)` does (e.g., in the example above it will return either `[0,1]` or `[1,0]`.
 - adding an offset to the list to align it to its respective domain: this is what the `+ i * bs` does (e.g. it would be `2*0=0` for the domain `a`, `2*1=2` for domain `b` and `2*2=4` for domain `c`). 
 - concatenating everything per domain. Note that since we go domain by domain with the for loop, **without** changing the domain index `i` when adding the offset `i*bs`. Hence, the order of domains within the batch will be preserved.  An example output can be:
 `permuted_within_dom = [1,0,2,3,5,4]` that would correspond in sampling `[a2,a1,b1,b2,c2,c1]`, which will then be compared to the original set `[a1,a2,b1,b2,c1,c2]` performing within domain mixing.

Similarly `permuted_across_dom` is obtained by:
 - randomly permuting a list of indices going from 0 to `bs-1` with `torch.randperm(bs)` (same as above).
 - adding an offset to the list to align it to its respective domain: this is what the `+ selected[i] * bs` does. **Note** that now we use `selected[i]` and not `i`, so the offset will correspond to a different domain due to how `selected` is constructed. 
 - concatenating everything per domain. Since now we create a discrepancy between domains and offsets, the order of domains within the batch will **not** be preserved.  An example output (with `selected=[2,0,1]`) can be:
 `permuted_across_dom = [4,5,1,0,3,2]` that would correspond in sampling `[c1,c2,a2,a1,b2,b1]`, which will then be compared to the original set `[a1,a2,b1,b2,c1,c2]` performing cross-domain mixing.
 
You can try out this snippet of code to understand how the various parts work:
```
import numpy as np
import torch

RG = np.random.default_rng()
def swap(xs, a, b):
    xs[a], xs[b] = xs[b], xs[a]

def derange(xs):
    x_new = [] + xs
    for a in range(1, len(x_new)):
        b = RG.choice(range(0, a))
        swap(x_new, a, b)
    return x_new

doms = list(range(len(torch.unique(domains))))
bs = domains.size(0) // len(doms)
selected = derange(doms)
print('Selected cross-domains',selected)

permuted_within_dom = torch.cat([(torch.randperm(bs) + i * bs) for i in range(len(doms))])
print('Within-domain mix indices',permuted_within_dom)

permuted_across_dom = torch.cat([(torch.randperm(bs) + selected[i] * bs) for i in range(len(doms))])
print('Cross-domain mix indices',permuted_across_dom)
```

**Comment by mvp18** [comment]
@mancinimassimiliano Thanks a lot for your prompt reply and this very elaborate and clear explanation. What I missed was that the dataloader returns batches that are ordered across domains through your ```BalancedSampler```. That's why my dummy batch didn't produce the desired output. But it all makes sense now, thanks.

**Comment by mancinimassimiliano** [comment]
@mvp18 happy it helped! I will close this issue but feel free to re-open it (or others) in case you spot some unclear parts (I am planning to release an extended version of this code including other baselines and more benchmarks, thus it will be helpful to comment/organize the code in a clearer way).

**Comment by mvp18** [comment]
@mancinimassimiliano great! Looking forward to it. Really nice paper btw, about time someone started ZSL+DG.

**Comment by mancinimassimiliano** [comment]
Thank you very much! :)
