### ISSUE TITLE
How exactly the `final classifier' is being trained for DG+ZSL?

### ISSUE THREAD

**Issue by WilliamYi96** [mancinimassimiliano/CuMix#5]
Hi @mancinimassimiliano, I'm very glad to see your good work CuMix. I can understand the `train classifier' is being trained by [methods.py#L309](https://github.com/mancinimassimiliano/CuMix/blob/master/methods.py#L309). However, I can not find any clue how the final classifier in your case is being trained. Can you please provide some help?

**Comment by mancinimassimiliano** [comment]
Hi @WilliamYi96. We exchanged emails, but I post my answer here as well, in case someone may find it useful. 

As written in the paper, in ZSL the classifier is fixed and initialized with word embeddings. This means the classifier is actually not trained, but what is learned is the semantic projector from visual features to word embeddings. This applies also to the ZSL+DG setting. Note that there is no way to train the final classifier in ZSL settings since no images are available for unseen classes (to be precise, this actually is dependent on the ZSL method).

In DG instead, the `self.final_classifier` and the `self.train_classifier` are trained and are the same, while the semantic projector is just an identity function. 

In the code, this can be seen from the effect of the `dg_only` (i.e. indicating the DG setting) flag. [Here](https://github.com/mancinimassimiliano/CuMix/blob/master/methods.py#L117), you can see the different initialization for DG, and [here](https://github.com/mancinimassimiliano/CuMix/blob/master/methods.py#L155), how different parameters are passed to the optimizer in the case of DG. In DG, train and final classifiers are synchronized every time the "[to](https://github.com/mancinimassimiliano/CuMix/blob/master/methods.py#L180)" function is called (this may be sub optimal).
